# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Account.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rAccount.proto\x1a\x0c\x43ommon.proto\"4\n\x0f\x43S_AccountLogin\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"M\n\x12\x43S_AccountRegister\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\x14\n\x05\x65mail\x18\x03 \x01(\t:\x05\x65mail\"\x92\x01\n\x0fSC_AccountLogin\x12#\n\x0bserverInfos\x18\x01 \x03(\x0b\x32\x0e.VO_ServerInfo\x12\"\n\nlastServer\x18\x02 \x01(\x0b\x32\x0e.VO_ServerInfo\x12(\n\x10recommendServers\x18\x03 \x03(\x0b\x32\x0e.VO_ServerInfo\x12\x0c\n\x04info\x18\x04 \x01(\t\"c\n\x12SC_AccountRegister\x12#\n\x0bserverInfos\x18\x01 \x03(\x0b\x32\x0e.VO_ServerInfo\x12(\n\x10recommendServers\x18\x02 \x03(\x0b\x32\x0e.VO_ServerInfoB5\n$com.fanxing.server.io.proto.protocolB\rAccountProtos')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,])




_CS_ACCOUNTLOGIN = _descriptor.Descriptor(
  name='CS_AccountLogin',
  full_name='CS_AccountLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='CS_AccountLogin.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='CS_AccountLogin.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=83,
)


_CS_ACCOUNTREGISTER = _descriptor.Descriptor(
  name='CS_AccountRegister',
  full_name='CS_AccountRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='CS_AccountRegister.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='CS_AccountRegister.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='CS_AccountRegister.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("email").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=162,
)


_SC_ACCOUNTLOGIN = _descriptor.Descriptor(
  name='SC_AccountLogin',
  full_name='SC_AccountLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverInfos', full_name='SC_AccountLogin.serverInfos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastServer', full_name='SC_AccountLogin.lastServer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recommendServers', full_name='SC_AccountLogin.recommendServers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='SC_AccountLogin.info', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=311,
)


_SC_ACCOUNTREGISTER = _descriptor.Descriptor(
  name='SC_AccountRegister',
  full_name='SC_AccountRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverInfos', full_name='SC_AccountRegister.serverInfos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recommendServers', full_name='SC_AccountRegister.recommendServers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=412,
)

_SC_ACCOUNTLOGIN.fields_by_name['serverInfos'].message_type = Common__pb2._VO_SERVERINFO
_SC_ACCOUNTLOGIN.fields_by_name['lastServer'].message_type = Common__pb2._VO_SERVERINFO
_SC_ACCOUNTLOGIN.fields_by_name['recommendServers'].message_type = Common__pb2._VO_SERVERINFO
_SC_ACCOUNTREGISTER.fields_by_name['serverInfos'].message_type = Common__pb2._VO_SERVERINFO
_SC_ACCOUNTREGISTER.fields_by_name['recommendServers'].message_type = Common__pb2._VO_SERVERINFO
DESCRIPTOR.message_types_by_name['CS_AccountLogin'] = _CS_ACCOUNTLOGIN
DESCRIPTOR.message_types_by_name['CS_AccountRegister'] = _CS_ACCOUNTREGISTER
DESCRIPTOR.message_types_by_name['SC_AccountLogin'] = _SC_ACCOUNTLOGIN
DESCRIPTOR.message_types_by_name['SC_AccountRegister'] = _SC_ACCOUNTREGISTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CS_AccountLogin = _reflection.GeneratedProtocolMessageType('CS_AccountLogin', (_message.Message,), dict(
  DESCRIPTOR = _CS_ACCOUNTLOGIN,
  __module__ = 'Account_pb2'
  # @@protoc_insertion_point(class_scope:CS_AccountLogin)
  ))
_sym_db.RegisterMessage(CS_AccountLogin)

CS_AccountRegister = _reflection.GeneratedProtocolMessageType('CS_AccountRegister', (_message.Message,), dict(
  DESCRIPTOR = _CS_ACCOUNTREGISTER,
  __module__ = 'Account_pb2'
  # @@protoc_insertion_point(class_scope:CS_AccountRegister)
  ))
_sym_db.RegisterMessage(CS_AccountRegister)

SC_AccountLogin = _reflection.GeneratedProtocolMessageType('SC_AccountLogin', (_message.Message,), dict(
  DESCRIPTOR = _SC_ACCOUNTLOGIN,
  __module__ = 'Account_pb2'
  # @@protoc_insertion_point(class_scope:SC_AccountLogin)
  ))
_sym_db.RegisterMessage(SC_AccountLogin)

SC_AccountRegister = _reflection.GeneratedProtocolMessageType('SC_AccountRegister', (_message.Message,), dict(
  DESCRIPTOR = _SC_ACCOUNTREGISTER,
  __module__ = 'Account_pb2'
  # @@protoc_insertion_point(class_scope:SC_AccountRegister)
  ))
_sym_db.RegisterMessage(SC_AccountRegister)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.fanxing.server.io.proto.protocolB\rAccountProtos'))
# @@protoc_insertion_point(module_scope)
