# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageId.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageId.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fMessageId.proto*\xa4\x04\n\tMessageId\x12\x16\n\x11MICS_VersionCheck\x10\xe9\x07\x12\x1a\n\x15MISC_VersionCheckResp\x10\xea\x07\x12\x17\n\x12MICS_GetServerList\x10\xeb\x07\x12\x1b\n\x16MISC_GetServerListResp\x10\xec\x07\x12\x18\n\x13MICS_AfreshLoadData\x10\xed\x07\x12\x1c\n\x17MISC_AfreshLoadDataResp\x10\xee\x07\x12\x13\n\x0eMICS_SendEmail\x10\xef\x07\x12\x17\n\x12MISC_SendEmailResp\x10\xf0\x07\x12\x19\n\x14MICS_GetLoadProgress\x10\xf1\x07\x12\x1d\n\x18MISC_GetLoadProgressResp\x10\xf2\x07\x12\x0f\n\nMICS_Login\x10\xf3\x07\x12\x13\n\x0eMISC_LoginResp\x10\xf4\x07\x12\x1a\n\x15MICS_LoadAuthenticate\x10\xf5\x07\x12\x1e\n\x19MISC_LoadAuthenticateResp\x10\xf6\x07\x12\x0f\n\nMIVO_Error\x10\xf7\x07\x12\x14\n\x0fMICS_SendNovice\x10\xf8\x07\x12\x18\n\x13MISC_SendNoviceResp\x10\xf9\x07\x12\x16\n\x11MICS_BannedPlayer\x10\xfa\x07\x12\x1a\n\x15MISC_BannedPlayerResp\x10\xfb\x07\x12\x18\n\x13MICS_RefreshDiamond\x10\xfd\x07\x12\x1c\n\x17MISC_RefreshDiamondResp\x10\xfe\x07\x42\x32\n com.fanxing.GMServer.io.protocolB\x0eMessageIdProto')
)

_MESSAGEID = _descriptor.EnumDescriptor(
  name='MessageId',
  full_name='MessageId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MICS_VersionCheck', index=0, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_VersionCheckResp', index=1, number=1002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_GetServerList', index=2, number=1003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_GetServerListResp', index=3, number=1004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_AfreshLoadData', index=4, number=1005,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_AfreshLoadDataResp', index=5, number=1006,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_SendEmail', index=6, number=1007,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_SendEmailResp', index=7, number=1008,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_GetLoadProgress', index=8, number=1009,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_GetLoadProgressResp', index=9, number=1010,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_Login', index=10, number=1011,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_LoginResp', index=11, number=1012,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_LoadAuthenticate', index=12, number=1013,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_LoadAuthenticateResp', index=13, number=1014,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIVO_Error', index=14, number=1015,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_SendNovice', index=15, number=1016,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_SendNoviceResp', index=16, number=1017,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_BannedPlayer', index=17, number=1018,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_BannedPlayerResp', index=18, number=1019,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MICS_RefreshDiamond', index=19, number=1021,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISC_RefreshDiamondResp', index=20, number=1022,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=20,
  serialized_end=568,
)
_sym_db.RegisterEnumDescriptor(_MESSAGEID)

MessageId = enum_type_wrapper.EnumTypeWrapper(_MESSAGEID)
MICS_VersionCheck = 1001
MISC_VersionCheckResp = 1002
MICS_GetServerList = 1003
MISC_GetServerListResp = 1004
MICS_AfreshLoadData = 1005
MISC_AfreshLoadDataResp = 1006
MICS_SendEmail = 1007
MISC_SendEmailResp = 1008
MICS_GetLoadProgress = 1009
MISC_GetLoadProgressResp = 1010
MICS_Login = 1011
MISC_LoginResp = 1012
MICS_LoadAuthenticate = 1013
MISC_LoadAuthenticateResp = 1014
MIVO_Error = 1015
MICS_SendNovice = 1016
MISC_SendNoviceResp = 1017
MICS_BannedPlayer = 1018
MISC_BannedPlayerResp = 1019
MICS_RefreshDiamond = 1021
MISC_RefreshDiamondResp = 1022


DESCRIPTOR.enum_types_by_name['MessageId'] = _MESSAGEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.fanxing.GMServer.io.protocolB\016MessageIdProto'))
# @@protoc_insertion_point(module_scope)
