# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Help.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Quest_pb2 as Quest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Help.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\nHelp.proto\x1a\x0bQuest.proto\"\x0e\n\x0c\x43S_HelpDatas\"4\n\x11\x43S_GetDailyReward\x12\x10\n\x08rewardId\x18\x01 \x02(\x05\x12\r\n\x05patch\x18\x02 \x01(\x08\"%\n\x14\x43S_GetLivenessReward\x12\r\n\x05\x62oxId\x18\x01 \x02(\x05\"W\n\x0cSC_HelpDatas\x12\x19\n\x06quests\x18\x01 \x03(\x0b\x32\t.VO_Quest\x12\x19\n\x11\x64\x61ilyRewardIdList\x18\x02 \x03(\x05\x12\x11\n\tboxIdList\x18\x03 \x03(\x05\x42\x32\n$com.fanxing.server.io.proto.protocolB\nHelpProtos')
  ,
  dependencies=[Quest__pb2.DESCRIPTOR,])




_CS_HELPDATAS = _descriptor.Descriptor(
  name='CS_HelpDatas',
  full_name='CS_HelpDatas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=41,
)


_CS_GETDAILYREWARD = _descriptor.Descriptor(
  name='CS_GetDailyReward',
  full_name='CS_GetDailyReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rewardId', full_name='CS_GetDailyReward.rewardId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='patch', full_name='CS_GetDailyReward.patch', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=95,
)


_CS_GETLIVENESSREWARD = _descriptor.Descriptor(
  name='CS_GetLivenessReward',
  full_name='CS_GetLivenessReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boxId', full_name='CS_GetLivenessReward.boxId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=134,
)


_SC_HELPDATAS = _descriptor.Descriptor(
  name='SC_HelpDatas',
  full_name='SC_HelpDatas',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quests', full_name='SC_HelpDatas.quests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dailyRewardIdList', full_name='SC_HelpDatas.dailyRewardIdList', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boxIdList', full_name='SC_HelpDatas.boxIdList', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=223,
)

_SC_HELPDATAS.fields_by_name['quests'].message_type = Quest__pb2._VO_QUEST
DESCRIPTOR.message_types_by_name['CS_HelpDatas'] = _CS_HELPDATAS
DESCRIPTOR.message_types_by_name['CS_GetDailyReward'] = _CS_GETDAILYREWARD
DESCRIPTOR.message_types_by_name['CS_GetLivenessReward'] = _CS_GETLIVENESSREWARD
DESCRIPTOR.message_types_by_name['SC_HelpDatas'] = _SC_HELPDATAS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CS_HelpDatas = _reflection.GeneratedProtocolMessageType('CS_HelpDatas', (_message.Message,), dict(
  DESCRIPTOR = _CS_HELPDATAS,
  __module__ = 'Help_pb2'
  # @@protoc_insertion_point(class_scope:CS_HelpDatas)
  ))
_sym_db.RegisterMessage(CS_HelpDatas)

CS_GetDailyReward = _reflection.GeneratedProtocolMessageType('CS_GetDailyReward', (_message.Message,), dict(
  DESCRIPTOR = _CS_GETDAILYREWARD,
  __module__ = 'Help_pb2'
  # @@protoc_insertion_point(class_scope:CS_GetDailyReward)
  ))
_sym_db.RegisterMessage(CS_GetDailyReward)

CS_GetLivenessReward = _reflection.GeneratedProtocolMessageType('CS_GetLivenessReward', (_message.Message,), dict(
  DESCRIPTOR = _CS_GETLIVENESSREWARD,
  __module__ = 'Help_pb2'
  # @@protoc_insertion_point(class_scope:CS_GetLivenessReward)
  ))
_sym_db.RegisterMessage(CS_GetLivenessReward)

SC_HelpDatas = _reflection.GeneratedProtocolMessageType('SC_HelpDatas', (_message.Message,), dict(
  DESCRIPTOR = _SC_HELPDATAS,
  __module__ = 'Help_pb2'
  # @@protoc_insertion_point(class_scope:SC_HelpDatas)
  ))
_sym_db.RegisterMessage(SC_HelpDatas)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.fanxing.server.io.proto.protocolB\nHelpProtos'))
# @@protoc_insertion_point(module_scope)
