# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Notify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Struct_pb2 as Struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Notify.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cNotify.proto\x1a\x0cStruct.proto\"*\n\x0c\x43S_GetNotify\x12\x1a\n\x05types\x18\x01 \x03(\x0e\x32\x0b.NotifyType\"+\n\x0b\x43S_GetLocks\x12\x1c\n\x05types\x18\x01 \x03(\x0e\x32\r.LockMarkType\".\n\x0e\x43S_GetLastTime\x12\x1c\n\x05types\x18\x01 \x03(\x0e\x32\r.LastTimeType\"5\n\tVO_Notify\x12\x19\n\x04type\x18\x01 \x02(\x0e\x32\x0b.NotifyType\x12\r\n\x05value\x18\x02 \x02(\x05\",\n\x0cSC_GetNotify\x12\x1c\n\x08notifies\x18\x01 \x03(\x0b\x32\n.VO_Notify\"&\n\x0bSC_GetLocks\x12\x17\n\x05locks\x18\x01 \x03(\x0b\x32\x08.VO_Lock\"1\n\x0eSC_GetLastTime\x12\x1f\n\tlastTimes\x18\x01 \x03(\x0b\x32\x0c.VO_LastTime*\xf3\x03\n\nNotifyType\x12\n\n\x06\x42\x41TTLE\x10\x01\x12\t\n\x05STORE\x10\x02\x12\x0c\n\x08\x41\x43TIVITY\x10\x03\x12\x13\n\x0fTANKMANUFACTURE\x10\x04\x12\r\n\tCOMMANDER\x10\x05\x12\x11\n\rSUPPLUSTATION\x10\x06\x12\r\n\tFORMAITON\x10\x07\x12\x13\n\x0fGACHA_COMMANDER\x10\x08\x12\t\n\x05\x44\x45POT\x10\t\x12\x0b\n\x07GUNROOM\x10\n\x12\x0b\n\x07MISSION\x10\x0b\x12\x0c\n\x08\x41RMYCORP\x10\x0c\x12\x0b\n\x07POKEDEX\x10\r\x12\n\n\x06\x46RIEND\x10\x0e\x12\t\n\x05\x45MAIL\x10\x0f\x12\x08\n\x04\x43HAT\x10\x10\x12\x10\n\x0c\x41NNOUNCEMENT\x10\x11\x12\x07\n\x03SET\x10\x12\x12\x07\n\x03OIL\x10\x13\x12\x12\n\x0e\x41\x43TIVITYCENTER\x10\x14\x12\x11\n\rWELFARECENTER\x10\x15\x12\n\n\x06SIGNIN\x10\x16\x12\x11\n\rCONSUMEREWARD\x10\x17\x12\x17\n\x13OPENSERVICECARNIVAL\x10\x18\x12\x10\n\x0cZLDZZ_IRRUPT\x10\x19\x12\x0f\n\x0bVIPBuyMoney\x10\x1a\x12\x11\n\rLTDJ_DayCount\x10\x1b\x12\x0f\n\x0bLOGINREWARD\x10\x1c\x12\x11\n\rLEVELUPREWARD\x10\x1d\x12\x0e\n\nDAILYGOALS\x10\x1e\x12\r\n\tLOGINSTAR\x10\x1f\x12\x08\n\x04RANK\x10 B4\n$com.fanxing.server.io.proto.protocolB\x0cNotifyProtos')
  ,
  dependencies=[Struct__pb2.DESCRIPTOR,])

_NOTIFYTYPE = _descriptor.EnumDescriptor(
  name='NotifyType',
  full_name='NotifyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BATTLE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITY', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TANKMANUFACTURE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMANDER', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUPPLUSTATION', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORMAITON', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GACHA_COMMANDER', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEPOT', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GUNROOM', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSION', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARMYCORP', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEDEX', index=12, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRIEND', index=13, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=14, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT', index=15, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANNOUNCEMENT', index=16, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET', index=17, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OIL', index=18, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVITYCENTER', index=19, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WELFARECENTER', index=20, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGNIN', index=21, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSUMEREWARD', index=22, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPENSERVICECARNIVAL', index=23, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZLDZZ_IRRUPT', index=24, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIPBuyMoney', index=25, number=26,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LTDJ_DayCount', index=26, number=27,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGINREWARD', index=27, number=28,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVELUPREWARD', index=28, number=29,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAILYGOALS', index=29, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGINSTAR', index=30, number=31,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RANK', index=31, number=32,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=360,
  serialized_end=859,
)
_sym_db.RegisterEnumDescriptor(_NOTIFYTYPE)

NotifyType = enum_type_wrapper.EnumTypeWrapper(_NOTIFYTYPE)
BATTLE = 1
STORE = 2
ACTIVITY = 3
TANKMANUFACTURE = 4
COMMANDER = 5
SUPPLUSTATION = 6
FORMAITON = 7
GACHA_COMMANDER = 8
DEPOT = 9
GUNROOM = 10
MISSION = 11
ARMYCORP = 12
POKEDEX = 13
FRIEND = 14
EMAIL = 15
CHAT = 16
ANNOUNCEMENT = 17
SET = 18
OIL = 19
ACTIVITYCENTER = 20
WELFARECENTER = 21
SIGNIN = 22
CONSUMEREWARD = 23
OPENSERVICECARNIVAL = 24
ZLDZZ_IRRUPT = 25
VIPBuyMoney = 26
LTDJ_DayCount = 27
LOGINREWARD = 28
LEVELUPREWARD = 29
DAILYGOALS = 30
LOGINSTAR = 31
RANK = 32



_CS_GETNOTIFY = _descriptor.Descriptor(
  name='CS_GetNotify',
  full_name='CS_GetNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='CS_GetNotify.types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=72,
)


_CS_GETLOCKS = _descriptor.Descriptor(
  name='CS_GetLocks',
  full_name='CS_GetLocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='CS_GetLocks.types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=117,
)


_CS_GETLASTTIME = _descriptor.Descriptor(
  name='CS_GetLastTime',
  full_name='CS_GetLastTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='CS_GetLastTime.types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=165,
)


_VO_NOTIFY = _descriptor.Descriptor(
  name='VO_Notify',
  full_name='VO_Notify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='VO_Notify.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='VO_Notify.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=220,
)


_SC_GETNOTIFY = _descriptor.Descriptor(
  name='SC_GetNotify',
  full_name='SC_GetNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notifies', full_name='SC_GetNotify.notifies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=266,
)


_SC_GETLOCKS = _descriptor.Descriptor(
  name='SC_GetLocks',
  full_name='SC_GetLocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locks', full_name='SC_GetLocks.locks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=306,
)


_SC_GETLASTTIME = _descriptor.Descriptor(
  name='SC_GetLastTime',
  full_name='SC_GetLastTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lastTimes', full_name='SC_GetLastTime.lastTimes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=357,
)

_CS_GETNOTIFY.fields_by_name['types'].enum_type = _NOTIFYTYPE
_CS_GETLOCKS.fields_by_name['types'].enum_type = Struct__pb2._LOCKMARKTYPE
_CS_GETLASTTIME.fields_by_name['types'].enum_type = Struct__pb2._LASTTIMETYPE
_VO_NOTIFY.fields_by_name['type'].enum_type = _NOTIFYTYPE
_SC_GETNOTIFY.fields_by_name['notifies'].message_type = _VO_NOTIFY
_SC_GETLOCKS.fields_by_name['locks'].message_type = Struct__pb2._VO_LOCK
_SC_GETLASTTIME.fields_by_name['lastTimes'].message_type = Struct__pb2._VO_LASTTIME
DESCRIPTOR.message_types_by_name['CS_GetNotify'] = _CS_GETNOTIFY
DESCRIPTOR.message_types_by_name['CS_GetLocks'] = _CS_GETLOCKS
DESCRIPTOR.message_types_by_name['CS_GetLastTime'] = _CS_GETLASTTIME
DESCRIPTOR.message_types_by_name['VO_Notify'] = _VO_NOTIFY
DESCRIPTOR.message_types_by_name['SC_GetNotify'] = _SC_GETNOTIFY
DESCRIPTOR.message_types_by_name['SC_GetLocks'] = _SC_GETLOCKS
DESCRIPTOR.message_types_by_name['SC_GetLastTime'] = _SC_GETLASTTIME
DESCRIPTOR.enum_types_by_name['NotifyType'] = _NOTIFYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CS_GetNotify = _reflection.GeneratedProtocolMessageType('CS_GetNotify', (_message.Message,), dict(
  DESCRIPTOR = _CS_GETNOTIFY,
  __module__ = 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:CS_GetNotify)
  ))
_sym_db.RegisterMessage(CS_GetNotify)

CS_GetLocks = _reflection.GeneratedProtocolMessageType('CS_GetLocks', (_message.Message,), dict(
  DESCRIPTOR = _CS_GETLOCKS,
  __module__ = 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:CS_GetLocks)
  ))
_sym_db.RegisterMessage(CS_GetLocks)

CS_GetLastTime = _reflection.GeneratedProtocolMessageType('CS_GetLastTime', (_message.Message,), dict(
  DESCRIPTOR = _CS_GETLASTTIME,
  __module__ = 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:CS_GetLastTime)
  ))
_sym_db.RegisterMessage(CS_GetLastTime)

VO_Notify = _reflection.GeneratedProtocolMessageType('VO_Notify', (_message.Message,), dict(
  DESCRIPTOR = _VO_NOTIFY,
  __module__ = 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:VO_Notify)
  ))
_sym_db.RegisterMessage(VO_Notify)

SC_GetNotify = _reflection.GeneratedProtocolMessageType('SC_GetNotify', (_message.Message,), dict(
  DESCRIPTOR = _SC_GETNOTIFY,
  __module__ = 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:SC_GetNotify)
  ))
_sym_db.RegisterMessage(SC_GetNotify)

SC_GetLocks = _reflection.GeneratedProtocolMessageType('SC_GetLocks', (_message.Message,), dict(
  DESCRIPTOR = _SC_GETLOCKS,
  __module__ = 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:SC_GetLocks)
  ))
_sym_db.RegisterMessage(SC_GetLocks)

SC_GetLastTime = _reflection.GeneratedProtocolMessageType('SC_GetLastTime', (_message.Message,), dict(
  DESCRIPTOR = _SC_GETLASTTIME,
  __module__ = 'Notify_pb2'
  # @@protoc_insertion_point(class_scope:SC_GetLastTime)
  ))
_sym_db.RegisterMessage(SC_GetLastTime)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.fanxing.server.io.proto.protocolB\014NotifyProtos'))
# @@protoc_insertion_point(module_scope)
