# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlatformAccount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Account_pb2 as Account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlatformAccount.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15PlatformAccount.proto\x1a\x0c\x43ommon.proto\x1a\rAccount.proto\"6\n\x10\x43S_PlatformLogin\x12\x13\n\x0b\x61\x63\x63ountType\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x02(\t*J\n\x0cUCLoginState\x12\x0b\n\x07success\x10\x01\x12\x0e\n\nparamError\x10\n\x12\x0c\n\x08notLogin\x10\x0b\x12\x0f\n\x0bserverError\x10\x63*L\n\rYsdkLoginType\x12\x13\n\x0fyePlatform_None\x10\x00\x12\x14\n\x10yPlatform_Weixin\x10\x02\x12\x10\n\x0cyPlatform_QQ\x10\x01*8\n\x0eYsdkOrderState\x12\n\n\x06normal\x10\x01\x12\x0c\n\x08unnormal\x10\x02\x12\x0c\n\x08unchange\x10\x03\x42=\n$com.fanxing.server.io.proto.protocolB\x15PlatformAccountProtos')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,Account__pb2.DESCRIPTOR,])

_UCLOGINSTATE = _descriptor.EnumDescriptor(
  name='UCLoginState',
  full_name='UCLoginState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='success', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='paramError', index=1, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='notLogin', index=2, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='serverError', index=3, number=99,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=110,
  serialized_end=184,
)
_sym_db.RegisterEnumDescriptor(_UCLOGINSTATE)

UCLoginState = enum_type_wrapper.EnumTypeWrapper(_UCLOGINSTATE)
_YSDKLOGINTYPE = _descriptor.EnumDescriptor(
  name='YsdkLoginType',
  full_name='YsdkLoginType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='yePlatform_None', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='yPlatform_Weixin', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='yPlatform_QQ', index=2, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=186,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_YSDKLOGINTYPE)

YsdkLoginType = enum_type_wrapper.EnumTypeWrapper(_YSDKLOGINTYPE)
_YSDKORDERSTATE = _descriptor.EnumDescriptor(
  name='YsdkOrderState',
  full_name='YsdkOrderState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='normal', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='unnormal', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='unchange', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=264,
  serialized_end=320,
)
_sym_db.RegisterEnumDescriptor(_YSDKORDERSTATE)

YsdkOrderState = enum_type_wrapper.EnumTypeWrapper(_YSDKORDERSTATE)
success = 1
paramError = 10
notLogin = 11
serverError = 99
yePlatform_None = 0
yPlatform_Weixin = 2
yPlatform_QQ = 1
normal = 1
unnormal = 2
unchange = 3



_CS_PLATFORMLOGIN = _descriptor.Descriptor(
  name='CS_PlatformLogin',
  full_name='CS_PlatformLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountType', full_name='CS_PlatformLogin.accountType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='CS_PlatformLogin.param', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['CS_PlatformLogin'] = _CS_PLATFORMLOGIN
DESCRIPTOR.enum_types_by_name['UCLoginState'] = _UCLOGINSTATE
DESCRIPTOR.enum_types_by_name['YsdkLoginType'] = _YSDKLOGINTYPE
DESCRIPTOR.enum_types_by_name['YsdkOrderState'] = _YSDKORDERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CS_PlatformLogin = _reflection.GeneratedProtocolMessageType('CS_PlatformLogin', (_message.Message,), dict(
  DESCRIPTOR = _CS_PLATFORMLOGIN,
  __module__ = 'PlatformAccount_pb2'
  # @@protoc_insertion_point(class_scope:CS_PlatformLogin)
  ))
_sym_db.RegisterMessage(CS_PlatformLogin)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.fanxing.server.io.proto.protocolB\025PlatformAccountProtos'))
# @@protoc_insertion_point(module_scope)
