# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Props.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Struct_pb2 as Struct__pb2
import Role_pb2 as Role__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Props.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bProps.proto\x1a\x0cStruct.proto\x1a\nRole.proto\"H\n\x0b\x43S_UseProps\x12\x12\n\ninstanceId\x18\x01 \x02(\x05\x12\x13\n\x07useToId\x18\x02 \x01(\x05:\x02-1\x12\x10\n\x05\x63ount\x18\x03 \x01(\x05:\x01\x31\"8\n\x10\x43S_UseDepotProps\x12\x12\n\ninstanceId\x18\x01 \x02(\x05\x12\x10\n\x05\x63ount\x18\x03 \x01(\x05:\x01\x31\"1\n\x0c\x43S_PropsSell\x12\x12\n\ninstanceId\x18\x01 \x02(\x05\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\"7\n\x0f\x43S_PropsCompose\x12\x12\n\ntemplateId\x18\x01 \x02(\x05\x12\x10\n\x05\x63ount\x18\x02 \x01(\x05:\x01\x31\"7\n\x0f\x43S_PropsResolve\x12\x12\n\ninstanceId\x18\x01 \x02(\x05\x12\x10\n\x05\x63ount\x18\x02 \x01(\x05:\x01\x31\"g\n\x10SC_UseDepotProps\x12\"\n\nroleUpdate\x18\x01 \x02(\x0b\x32\x0e.VO_RoleUpdate\x12\x1d\n\x07rewards\x18\x02 \x03(\x0b\x32\x0c.VO_Supplies\x12\x10\n\x05\x63ount\x18\x03 \x01(\x05:\x01\x30\x42\x33\n$com.fanxing.server.io.proto.protocolB\x0bPropsProtos')
  ,
  dependencies=[Struct__pb2.DESCRIPTOR,Role__pb2.DESCRIPTOR,])




_CS_USEPROPS = _descriptor.Descriptor(
  name='CS_UseProps',
  full_name='CS_UseProps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='CS_UseProps.instanceId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='useToId', full_name='CS_UseProps.useToId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='CS_UseProps.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=113,
)


_CS_USEDEPOTPROPS = _descriptor.Descriptor(
  name='CS_UseDepotProps',
  full_name='CS_UseDepotProps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='CS_UseDepotProps.instanceId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='CS_UseDepotProps.count', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=171,
)


_CS_PROPSSELL = _descriptor.Descriptor(
  name='CS_PropsSell',
  full_name='CS_PropsSell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='CS_PropsSell.instanceId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='CS_PropsSell.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=222,
)


_CS_PROPSCOMPOSE = _descriptor.Descriptor(
  name='CS_PropsCompose',
  full_name='CS_PropsCompose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='templateId', full_name='CS_PropsCompose.templateId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='CS_PropsCompose.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=279,
)


_CS_PROPSRESOLVE = _descriptor.Descriptor(
  name='CS_PropsResolve',
  full_name='CS_PropsResolve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='CS_PropsResolve.instanceId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='CS_PropsResolve.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=336,
)


_SC_USEDEPOTPROPS = _descriptor.Descriptor(
  name='SC_UseDepotProps',
  full_name='SC_UseDepotProps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roleUpdate', full_name='SC_UseDepotProps.roleUpdate', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rewards', full_name='SC_UseDepotProps.rewards', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='SC_UseDepotProps.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=441,
)

_SC_USEDEPOTPROPS.fields_by_name['roleUpdate'].message_type = Role__pb2._VO_ROLEUPDATE
_SC_USEDEPOTPROPS.fields_by_name['rewards'].message_type = Struct__pb2._VO_SUPPLIES
DESCRIPTOR.message_types_by_name['CS_UseProps'] = _CS_USEPROPS
DESCRIPTOR.message_types_by_name['CS_UseDepotProps'] = _CS_USEDEPOTPROPS
DESCRIPTOR.message_types_by_name['CS_PropsSell'] = _CS_PROPSSELL
DESCRIPTOR.message_types_by_name['CS_PropsCompose'] = _CS_PROPSCOMPOSE
DESCRIPTOR.message_types_by_name['CS_PropsResolve'] = _CS_PROPSRESOLVE
DESCRIPTOR.message_types_by_name['SC_UseDepotProps'] = _SC_USEDEPOTPROPS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CS_UseProps = _reflection.GeneratedProtocolMessageType('CS_UseProps', (_message.Message,), dict(
  DESCRIPTOR = _CS_USEPROPS,
  __module__ = 'Props_pb2'
  # @@protoc_insertion_point(class_scope:CS_UseProps)
  ))
_sym_db.RegisterMessage(CS_UseProps)

CS_UseDepotProps = _reflection.GeneratedProtocolMessageType('CS_UseDepotProps', (_message.Message,), dict(
  DESCRIPTOR = _CS_USEDEPOTPROPS,
  __module__ = 'Props_pb2'
  # @@protoc_insertion_point(class_scope:CS_UseDepotProps)
  ))
_sym_db.RegisterMessage(CS_UseDepotProps)

CS_PropsSell = _reflection.GeneratedProtocolMessageType('CS_PropsSell', (_message.Message,), dict(
  DESCRIPTOR = _CS_PROPSSELL,
  __module__ = 'Props_pb2'
  # @@protoc_insertion_point(class_scope:CS_PropsSell)
  ))
_sym_db.RegisterMessage(CS_PropsSell)

CS_PropsCompose = _reflection.GeneratedProtocolMessageType('CS_PropsCompose', (_message.Message,), dict(
  DESCRIPTOR = _CS_PROPSCOMPOSE,
  __module__ = 'Props_pb2'
  # @@protoc_insertion_point(class_scope:CS_PropsCompose)
  ))
_sym_db.RegisterMessage(CS_PropsCompose)

CS_PropsResolve = _reflection.GeneratedProtocolMessageType('CS_PropsResolve', (_message.Message,), dict(
  DESCRIPTOR = _CS_PROPSRESOLVE,
  __module__ = 'Props_pb2'
  # @@protoc_insertion_point(class_scope:CS_PropsResolve)
  ))
_sym_db.RegisterMessage(CS_PropsResolve)

SC_UseDepotProps = _reflection.GeneratedProtocolMessageType('SC_UseDepotProps', (_message.Message,), dict(
  DESCRIPTOR = _SC_USEDEPOTPROPS,
  __module__ = 'Props_pb2'
  # @@protoc_insertion_point(class_scope:SC_UseDepotProps)
  ))
_sym_db.RegisterMessage(SC_UseDepotProps)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.fanxing.server.io.proto.protocolB\013PropsProtos'))
# @@protoc_insertion_point(module_scope)
