# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RobustAccount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Account_pb2 as Account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RobustAccount.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13RobustAccount.proto\x1a\x0c\x43ommon.proto\x1a\rAccount.proto\"C\n\x11\x43S_RobustSDKLogin\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x02(\t\x12\x0b\n\x03\x63id\x18\x02 \x02(\t\x12\x0c\n\x04\x63key\x18\x03 \x02(\tB;\n$com.fanxing.server.io.proto.protocolB\x13RobustAccountProtos')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,Account__pb2.DESCRIPTOR,])




_CS_ROBUSTSDKLOGIN = _descriptor.Descriptor(
  name='CS_RobustSDKLogin',
  full_name='CS_RobustSDKLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessToken', full_name='CS_RobustSDKLogin.accessToken', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cid', full_name='CS_RobustSDKLogin.cid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ckey', full_name='CS_RobustSDKLogin.ckey', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['CS_RobustSDKLogin'] = _CS_ROBUSTSDKLOGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CS_RobustSDKLogin = _reflection.GeneratedProtocolMessageType('CS_RobustSDKLogin', (_message.Message,), dict(
  DESCRIPTOR = _CS_ROBUSTSDKLOGIN,
  __module__ = 'RobustAccount_pb2'
  # @@protoc_insertion_point(class_scope:CS_RobustSDKLogin)
  ))
_sym_db.RegisterMessage(CS_RobustSDKLogin)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.fanxing.server.io.proto.protocolB\023RobustAccountProtos'))
# @@protoc_insertion_point(module_scope)
