# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TencentAccount.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Account_pb2 as Account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TencentAccount.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x14TencentAccount.proto\x1a\x0c\x43ommon.proto\x1a\rAccount.proto\"f\n\x13\x43S_TencentMSDKLogin\x12$\n\tloginType\x18\x01 \x02(\x0e\x32\x11.TencentLoginType\x12\x0e\n\x06openId\x18\x02 \x02(\t\x12\r\n\x05token\x18\x03 \x02(\t\x12\n\n\x02ip\x18\x04 \x02(\t*\x90\x01\n\x10TencentLoginType\x12\x12\n\x0e\x65Platform_None\x10\x00\x12\x14\n\x10\x65Platform_Weixin\x10\x01\x12\x10\n\x0c\x65Platform_QQ\x10\x02\x12\x15\n\x11\x65Platform_WTLogin\x10\x03\x12\x14\n\x10\x65Platform_QQHall\x10\x04\x12\x13\n\x0f\x65Platform_Guest\x10\x05\x42<\n$com.fanxing.server.io.proto.protocolB\x14TencentAccountProtos')
  ,
  dependencies=[Common__pb2.DESCRIPTOR,Account__pb2.DESCRIPTOR,])

_TENCENTLOGINTYPE = _descriptor.EnumDescriptor(
  name='TencentLoginType',
  full_name='TencentLoginType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ePlatform_None', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ePlatform_Weixin', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ePlatform_QQ', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ePlatform_WTLogin', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ePlatform_QQHall', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ePlatform_Guest', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=158,
  serialized_end=302,
)
_sym_db.RegisterEnumDescriptor(_TENCENTLOGINTYPE)

TencentLoginType = enum_type_wrapper.EnumTypeWrapper(_TENCENTLOGINTYPE)
ePlatform_None = 0
ePlatform_Weixin = 1
ePlatform_QQ = 2
ePlatform_WTLogin = 3
ePlatform_QQHall = 4
ePlatform_Guest = 5



_CS_TENCENTMSDKLOGIN = _descriptor.Descriptor(
  name='CS_TencentMSDKLogin',
  full_name='CS_TencentMSDKLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loginType', full_name='CS_TencentMSDKLogin.loginType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='openId', full_name='CS_TencentMSDKLogin.openId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='CS_TencentMSDKLogin.token', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='CS_TencentMSDKLogin.ip', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=155,
)

_CS_TENCENTMSDKLOGIN.fields_by_name['loginType'].enum_type = _TENCENTLOGINTYPE
DESCRIPTOR.message_types_by_name['CS_TencentMSDKLogin'] = _CS_TENCENTMSDKLOGIN
DESCRIPTOR.enum_types_by_name['TencentLoginType'] = _TENCENTLOGINTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CS_TencentMSDKLogin = _reflection.GeneratedProtocolMessageType('CS_TencentMSDKLogin', (_message.Message,), dict(
  DESCRIPTOR = _CS_TENCENTMSDKLOGIN,
  __module__ = 'TencentAccount_pb2'
  # @@protoc_insertion_point(class_scope:CS_TencentMSDKLogin)
  ))
_sym_db.RegisterMessage(CS_TencentMSDKLogin)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$com.fanxing.server.io.proto.protocolB\024TencentAccountProtos'))
# @@protoc_insertion_point(module_scope)
